//! Request and response data transfer objects for the sync protocol.

use serde::{Deserialize, Serialize};

/// Body for `POST /users/create`.
#[derive(Debug, Deserialize)]
pub(crate) struct UserCreateRequest {
    /// Username of the account to create.
    #[serde(default)]
    pub(crate) username: Option<String>,
    /// Password (already MD5-hashed by the client).
    #[serde(default)]
    pub(crate) password: Option<String>,
    /// Whether the new user may upload books. Defaults to `true`.
    #[serde(default)]
    pub(crate) can_upload: Option<bool>,
}

/// Body for `POST /users/create` success response.
#[derive(Debug, Serialize)]
pub(crate) struct UserCreateResponse {
    /// The created username.
    pub(crate) username: String,
}

/// Body for `GET /users/auth` success response.
#[derive(Debug, Serialize)]
pub(crate) struct AuthResponse {
    /// Always `"OK"` on success.
    pub(crate) authorized: &'static str,
}

/// Body for `PUT /syncs/progress`.
#[derive(Debug, Deserialize)]
pub(crate) struct ProgressRequest {
    /// Document identifier (a hash generated by the client).
    #[serde(default)]
    pub(crate) document: Option<String>,
    /// Reading progress position string.
    #[serde(default)]
    pub(crate) progress: Option<String>,
    /// Reading progress as a fraction.
    #[serde(default)]
    pub(crate) percentage: Option<f64>,
    /// Human-readable device name.
    #[serde(default)]
    pub(crate) device: Option<String>,
    /// Unique device identifier.
    #[serde(default)]
    pub(crate) device_id: Option<String>,
    /// Optional document metadata sent when `KOReader`'s "Send document
    /// metadata" setting is enabled.
    #[serde(default)]
    pub(crate) metadata: Option<ProgressMetadata>,
}

/// Document metadata sent alongside a progress update by `KOReader`.
#[derive(Debug, Deserialize)]
pub(crate) struct ProgressMetadata {
    /// The file name (basename) of the document on the device.
    #[serde(default)]
    pub(crate) filename: Option<String>,
    /// The document title.
    #[serde(default)]
    pub(crate) title: Option<String>,
    /// The authors. Accepts a plain string or an array of strings.
    #[serde(default, deserialize_with = "deserialize_authors")]
    pub(crate) authors: Option<String>,
}

fn deserialize_authors<'de, D>(deserializer: D) -> Result<Option<String>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = Option::<serde_json::Value>::deserialize(deserializer)?;
    Ok(value.map(normalize_authors))
}

/// Normalize an `authors` value (string or array) into a comma-separated string.
fn normalize_authors(value: serde_json::Value) -> String {
    match value {
        serde_json::Value::String(s) => s,
        serde_json::Value::Array(items) => {
            let names: Vec<String> = items
                .into_iter()
                .filter_map(|item| match item {
                    serde_json::Value::String(s) => Some(s),
                    serde_json::Value::Object(mut map) => map
                        .remove("name")
                        .and_then(|v| v.as_str().map(str::to_owned)),
                    _ => None,
                })
                .collect();
            names.join(", ")
        }
        _ => String::new(),
    }
}

/// Body for `PUT /syncs/progress` success response.
#[derive(Debug, Serialize)]
pub(crate) struct ProgressUpdateResponse {
    /// The document identifier.
    pub(crate) document: String,
    /// Server-assigned Unix timestamp (seconds).
    pub(crate) timestamp: i64,
}

/// Body for `GET /syncs/progress/:document` success response.
#[derive(Debug, Serialize)]
pub(crate) struct ProgressResponse {
    /// The document identifier.
    #[serde(rename = "document")]
    pub(crate) document_hash: String,
    /// Reading progress as a fraction.
    pub(crate) percentage: f64,
    /// Reading progress position string.
    pub(crate) progress: String,
    /// Human-readable device name.
    pub(crate) device: String,
    /// Unique device identifier, if known.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) device_id: Option<String>,
    /// Server-assigned Unix timestamp (seconds).
    pub(crate) timestamp: i64,
}

/// An empty JSON object, serialized as `{}`.
#[derive(Debug, Serialize)]
pub(crate) struct EmptyObject {}

/// Response body for `GET /syncs/progress/:document`: either the stored
/// progress or an empty object when the document is unknown.
#[derive(Debug, Serialize)]
#[serde(untagged)]
pub(crate) enum GetProgressResponse {
    /// The document exists; return its progress.
    Found(ProgressResponse),
    /// The document does not exist; return `{}`.
    Missing(EmptyObject),
}

/// Body for `GET /healthcheck`.
#[derive(Debug, Serialize)]
pub(crate) struct HealthResponse {
    /// Always `"OK"`.
    pub(crate) state: &'static str,
}

/// Body for `PUT /manage/users/password`.
#[derive(Debug, Deserialize)]
pub(crate) struct PasswordChangeRequest {
    /// New password (already MD5-hashed by the client).
    #[serde(default)]
    pub(crate) password: Option<String>,
}

/// Summary of a user returned by `GET /manage/users`.
#[derive(Debug, Serialize, sqlx::FromRow)]
pub(crate) struct UserSummary {
    /// Internal user id.
    pub(crate) id: i64,
    /// The username.
    pub(crate) username: String,
    /// Whether the user has administrator privileges.
    pub(crate) is_administrator: bool,
    /// Whether the user may log in and sync.
    pub(crate) is_active: bool,
    /// Whether the user may upload books to the shared library.
    pub(crate) can_upload: bool,
    /// Number of stored documents for the user.
    pub(crate) document_count: i64,
    /// Unix timestamp of the user's most recent sync, if any.
    pub(crate) last_synced: Option<i64>,
}

/// Generic message-only response used by management endpoints.
#[derive(Debug, Serialize)]
pub(crate) struct MessageResponse {
    /// The message.
    pub(crate) message: String,
}

impl MessageResponse {
    /// Create a message response.
    pub(crate) fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::normalize_authors;

    fn normalize(value: serde_json::Value) -> String {
        normalize_authors(value)
    }

    #[test]
    fn authors_string_is_kept_verbatim() {
        assert_eq!(normalize(serde_json::json!("Jane Doe")), "Jane Doe");
    }

    #[test]
    fn authors_array_of_strings_is_joined() {
        assert_eq!(normalize(serde_json::json!(["Alice", "Bob"])), "Alice, Bob");
    }

    #[test]
    fn authors_array_of_objects_uses_names() {
        assert_eq!(
            normalize(serde_json::json!([{"name": "Alice"}, {"name": "Bob"}])),
            "Alice, Bob"
        );
    }

    #[test]
    fn authors_other_types_yield_empty() {
        assert_eq!(normalize(serde_json::json!(42)), "");
    }
}
